### ISSUE TITLE
App doesn't fit the screen

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-SkeletonWearableApp#4]
Hello,
I am running your app on a Wear Round emulator API_22, and it doesn't properly fit the screen:
![screen](https://github-cloud.s3.amazonaws.com/assets/201209/10565083/788d33e2-7596-11e5-884c-db65869840d9.png)

Please advise if this is expected behavior.

Thank you,
Igor

**Comment by codingjeremy** [comment]
This sample has been deprecated.

Check out the link below for more information on how to properly fit your app to the screen:
https://developer.android.com/training/wearables/ui/layouts.html#same-layout
